EB-21 CA - Structure  create structure in CA folder and 2 hmtl file a…
LabiciIvan/exchange-bot pull request #23
Opened 2023-02-22 17:23 UTC by 1986-OldMan

…dded in pages folder,singin.html and singup.html

2023-02-22 20:36 UTC, LabiciIvan commented
@1986-OldMan  Please use the instruction guide on how to format the commit message [Exchange_Bot How ? Branch_name | Commit_message_title](https://github.com/LabiciIvan/exchange-bot/wiki/Exchange_Bot-How-%3F--Branch_name-%7C-Commit_message_title)
Your commit message looks like this **EB-21 CA - Structure create structure in CA folder and 2 hmtl file a… #23**
But it should be  **EB-21: CA - Structure #21**

2023-02-22 20:38 UTC, LabiciIvan requested changes
Why do you have changes in PRO ? 
You work on a CA task, you should have only changed files that are in CA folder.

2023-02-22 21:10 UTC, LabiciIvan reviewed
@1986-OldMan  Please use the instruction guide on how to format the commit message [Exchange_Bot How ? Branch_name | Commit_message_title](https://github.com/LabiciIvan/exchange-bot/wiki/Exchange_Bot-How-%3F--Branch_name-%7C-Commit_message_title)
Your commit message looks like this **EB-21 CA - Structure create structure in CA folder and 2 hmtl file a… #23**
But it should be  **EB-21: CA - Structure #21**

2023-02-23 03:04 UTC, 1986-OldMan commented
There are changes in PRO , because I have to uncomment on two lines of javascript code that you told me about.

Line 9 and line 21 of the code in PRO/app.js.

2023-02-23 03:06 UTC, 1986-OldMan commented
Ok ,I will look over the instructions one more time and redo it again.

2023-02-23 04:00 UTC, LabiciIvan commented
You only need to uncomment line **9** and line **21** of code in **Pro/app.js** just when you want to make tables in your database, otherwise you should keep it commented.

2023-02-23 04:01 UTC, LabiciIvan commented on PRO/app.js
> +let migrateRouter = require('./middleware/migrateBase');
Comment this line, almost most of the time we will let it be commented.

2023-02-23 04:02 UTC, LabiciIvan commented on PRO/app.js
> +app.use('/migrate', migrateRouter);
And this as well, keep it commented and only uncomment if you want to migrate database locally.

2023-02-24 17:57 UTC, closed without merging